### PR TITLE
Google icons instead of PNG for blocks

### PR DESCRIPTION
**Pull request by davidcommarmond**
The blocks in the footer make use of google material icons

However blocks in the timeline were still using PNG files

I've replaced all PNGs to make use of the same material icons in the footer for consistency + Make it easier to customise branding via CSS.

### CODE REVIEW

**Comment by davidcommarmond** [comment]
@Fleker just noticed that my google-cla agreement just got approved now.
Should I cancel this PR and do a new one so the cla/google check can pass ? Or you can do it from your side ?

Thanks

**Comment by Fleker** [comment]
Thanks for filing this PR. If you can figure out the emails this PR should be updated by the cla/google bot.

**Comment by davidcommarmond** [comment]
@Fleker ok CLA passed.
Thanks

**Comment by davidcommarmond** [comment]
Hi @Fleker , let me know if there's anything else pending before you approve this PR please ?

Thanks

**Comment by Fleker** [comment]
Sorry for the delay. I'll try to get to this by Friday at the latest.

**Comment by davidcommarmond** [comment]
No problem, thanks
Happy to look at other comments if needed.

**Review by Fleker — APPROVED** [review]
Thanks for doing this, I appreciate it! Looks good to me!

**Pull request merged**
